# Generated by Django 5.2.7 on 2025-11-05 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_post_author_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MaxLengthValidator(50, 'Category name cannot exceed 50 characters')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(100, 'Title cannot be longer than 100 characters')]),
        ),
    ]
